// Code generated by github.com/deweppro/go-static. DO NOT EDIT.
package api

func init() {
	//UI static archive
	UI = "H4sIAAAAAAAA/+yWQWvbMBTHc+6neL0NtkRyLWLwPI/uMDYojA1yGjto9nMkpkiu/NzEjH33IdvLaC45lLQN9f/yZL0n+z2b3x8zwcVC0cbMTifOOU+SpI+c88PI40Ts1/1+xEUiZsBP2NNebUPSz/iDn3U43JkoC98+v8gUyjK/AADISJPBfOX1F4swB8FFxoa9Id9Q928d9NOVHfzeXwZtpF9rm0LM7xTIlhzwPry9V7XVJakUBOf17n6GcEdzafTaplCgJfT/83+GJtjYRcaGzrPQRpgjygUXMIcbbX+BdQSVa22ZMRWF4rGK9VM/9bt/DmKVvH1q/oVYHvKfxBP/j6Lj/H+8/npe/F+XJay+3YzIF67EXBHVTcpY6/XCWWSv39+++26CQ1TOQ6OcJ7Tarn9krK9/OU7BtC1xd1oHOMb/Mro64D+6WiYT/4+hI/yfF/mfsLuEzyA3QAphhB0a9He6wMvREFScr2zlPLVWEpruzXAi/Cp0SOBRlh2QA1kUWBMEl2ig8m4DnWt7v6i9K7BptF1DOn+VMRUPt/3QEjTOWdgibLUxYGRrCwWSoGqNgULWstDULcYjL8VjJk2a9Dz1NwAA//8xWYePABAAAA=="
}

/* FILES:
/404.html
/faq.html
/index.html
*/
