// Code generated by github.com/deweppro/go-static. DO NOT EDIT.
package api

func init() {
	//UI static archive
	UI = "H4sIAAAAAAAA/+yWT2/TMBiHe96neHdDgtbOYjVSCEHjgECahEDqCXEwyZvammtnzuu1EeK7o/xhsF56QN1alOdiO7aTn2U9dpi2Je4WijZmdiw45zxJkr7knO+XfBldPdT751F0tUxmwI+W6C9CQ9LP+D9/a39xZ0LW7Xx+kSmUZX4BAJCRJoP5yutPFjM2tIaehtrf9Y7vrmzhx0OzYyP9WtsUYn6vQAZywPvi9aNRW12SSkFwXu8e9xDuaC6NXtsUCrSE/k//zyEEG1NkbMicdTG6FUT5B2wv4SPIDZBCCF4vnEVo0N/rAi8zpqJuXJyvbOU8BSsJTftqmGEdQYsEHmXZAjmQRYE1gdH2toHKuw20LkDlPNTeFdg02q4hnb/ImIqH174LBI1zFrYIW20MGBlsoUASVMEYKGQtC03tYpzCxuSs34Pn2X8muDiu/Yf9jxOx5z8XiZj8fwoO+A9zEFyc1ykguIA53Gh720tduWDL0f1TMO60YJW8e27/hVju+5/Ek/9PwmH/319/Pi//r8sSVl9uRuULV2KuiOomZWz8JWAv3969+drd7P193ijnCa22628Z68dPJ8XExMT/z68AAAD//0ZHdqwAEAAA"
}

/* FILES:
/index.html
/404.html
/faq.html
*/
