// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package shorten

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC7c61ac9DecodeGithubComOsspkgUriOneAppShorten(in *jlexer.Lexer, out *AddModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "url":
			out.URL = string(in.String())
		case "source":
			out.Source = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC7c61ac9EncodeGithubComOsspkgUriOneAppShorten(out *jwriter.Writer, in AddModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"url\":"
		out.RawString(prefix[1:])
		out.String(string(in.URL))
	}
	{
		const prefix string = ",\"source\":"
		out.RawString(prefix)
		out.String(string(in.Source))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AddModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC7c61ac9EncodeGithubComOsspkgUriOneAppShorten(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AddModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC7c61ac9EncodeGithubComOsspkgUriOneAppShorten(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AddModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC7c61ac9DecodeGithubComOsspkgUriOneAppShorten(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AddModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC7c61ac9DecodeGithubComOsspkgUriOneAppShorten(l, v)
}
